### ISSUE TITLE
Html layout

### ISSUE THREAD

**Issue by emmaparis** [emmaparis/Groupie-Gang#5]

**Comment by Smulchman** [comment]
- header
- colors ([this is our main palette](https://www.canva.com/colors/color-palettes/ocean-ripples/)) Our orange is #FA7A50
- body to hold carousel (carousel implemented elsewhere)

**Comment by JDR8888** [comment]
- header is now hero logo
 - colors need work - need to set border of card-headers (bulma seems to override)
 - carousel centered in body of page now
 - card images need tweaking

**Comment by emmaparis** [comment]
Working on colors now and setting all card color ways to be the same

**Comment by emmaparis** [comment]
Also adding unison font
